### ISSUE TITLE
Test errors on 1.5 due to ambiguities caused by type piracy

### ISSUE THREAD

**Issue by KristofferC** [JuliaMatrices/ArrayLayouts.jl#21]
This package and other dependencies fail on 1.5 due to ambiguities that this package introduces,

https://github.com/JuliaMatrices/ArrayLayouts.jl/blob/ba76345a24f0a6618fec80ab17193bfe7923543a/src/ArrayLayouts.jl#L83-L86

The test errors are of the form

```
  MethodError: unsafe_convert(::Type{Ptr{Float64}}, ::Adjoint{Float64,Array{Float64,2}}) is ambiguous. Candidates:
    unsafe_convert(::Type{Ptr{T}}, A::Adjoint{var"#s822",var"#s821"} where var"#s821"<:(StridedVecOrMat{T} where T) where var"#s822"<:Real) where T in LinearAlgebra at /opt/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:208
    unsafe_convert(::Type{Ptr{T}}, A::Adjoint{var"#s13",S} where S where var"#s13"<:Real) where T<:Real in ArrayLayouts at /home/pkgeval/.julia/packages/ArrayLayouts/S2dXf/src/ArrayLayouts.jl:83
  Possible fix, define
    unsafe_convert(::Type{Ptr{T}}, ::Adjoint{var"#s822",var"#s821"} where var"#s821"<:(StridedVecOrMat{T} where T) where var"#s822"<:Real) where T<:Real
```

It would be good to either remove these methods or try to get them into Base.

**Comment by dlfivefifty** [comment]
Right, these solved the same problem that a recent PR did https://github.com/JuliaLang/julia/pull/29135


So I think we just add an ` if VERSION < v”1.5-dev” ` to only do these type piracy where needed.

**Comment by KristofferC** [comment]
If possible, it would be nice with a fix and a release since it would clean up the results a bit for the next 1.5 PkgEval run.

**Comment by dlfivefifty** [comment]
Those definitions seemed unnecessarily strict as they only overloaded for `StridedARRAY` so I made a PR: https://github.com/JuliaLang/julia/pull/35929 

If you can get that merged we can partially avoid type piracy. We will still need the `ConjPtr` overloads so perhaps they can be moved to Base, let's discuss in the other PR.
