### ISSUE TITLE
Cholesky factorisations are not inferred

### ISSUE THREAD

**Issue by jipolanco** [JuliaMatrices/ArrayLayouts.jl#66]
The return type of Cholesky factorisations of banded matrices is not currently inferred.

Here is a minimum example showing this:

```julia
using LinearAlgebra
using BandedMatrices

M = BandedMatrix(Diagonal(rand(10)))
A = Hermitian(M)

@code_warntype cholesky!(A)
```

On Julia 1.6:

```julia
Variables
  #self#::Core.Const(LinearAlgebra.cholesky!)
  A::Hermitian{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}

Body::Any
1 ─ %1 = ArrayLayouts.Val(false)::Core.Const(Val{false}())
│   %2 = (#self#)(A, %1)::Any
└──      return %2
```

(The result is similar on Julia 1.7-beta2, and similar if one calls the out-of-place `cholesky`.)

This can be compared for instance to `qr(A)`, which is correctly inferred:

```julia
Variables
  #self#::Core.Const(LinearAlgebra.qr)
  A::Hermitian{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}
  args::Tuple{}

Body::LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
1 ─ %1 = Core.NamedTuple()::Core.Const(NamedTuple())
│   %2 = Base.pairs(%1)::Core.Const(Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())
│   %3 = Core.tuple(%2, #self#, A)::Core.PartialStruct(Tuple{Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(qr), Hermitian{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}}, Any[Core.Const(Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}()), Core.Const(LinearAlgebra.qr), Hermitian{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}}])
│   %4 = Core._apply_iterate(Base.iterate, ArrayLayouts.:(var"#qr#33"), %3, args)::LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}}
└──      return %4
```

The issue can be tracked down to an [`invoke` call in ArrayLayouts.jl](https://github.com/JuliaMatrices/ArrayLayouts.jl/blob/de884a0c07436883d3ca70d6a2d21f02059c4e36/src/factorizations.jl#L290) with the keyword argument `check::Bool`. Due to a [relatively old Julia issue](https://github.com/JuliaLang/julia/issues/29216), `invoke` calls with keyword arguments are not inferred.

If `invoke` is really needed there, perhaps it would be possible to workaround the issue by explicitly annotating the return type of `invoke`, as in `invoke(cholesky!, ...) :: Cholesky{eltype(A), typeof(parent(A))}`.

**Comment by dlfivefifty** [comment]
Thanks, I hand no idea that `invoke` does not support keyword arguments with type inference... annoying.

I think the easiest solution right now is to copy-and-paste the implementation for `cholesky!` from LinearAlgebra.jl, that is, we would get:
```julia
function _cholesky!(layout, axes, A, ::Val{false}=Val(false); check::Bool = true)
    C, info = _chol!(A.data, A.uplo == 'U' ? UpperTriangular : LowerTriangular)
    check && checkpositivedefinite(info)
    return Cholesky(C.data, A.uplo, info)
end
```
Are you happy to make a PR for this?

**Comment by jipolanco** [comment]
Sure, I'll take care of it!
